### ISSUE TITLE
Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files

### ISSUE THREAD

**Issue by jeancdc** [jasonmit/ember-cli-moment-shim#10]
I've got this bug when I execute `ember s`:

```
Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files
Error: Path or pattern "bower_components/ember-cli-moment-shim/moment-shim.js" did not match any files
    at Object.multiGlob (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:203:13)
    at Class.module.exports.CachingWriter.extend.addFiles (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
    at Class.module.exports.CachingWriter.extend.updateCache (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
    at /Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
    at lib$rsvp$$internal$$tryCatch (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
    at lib$rsvp$asap$$flush (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
    at process._tickCallback (node.js:355:11)
```

**Comment by jasonmit** [comment]
You are pulling in 0.3.x via bower, which is now an ember-addon so it should be installed via `ember install ember-cli-moment-shim` and you can remove the `app.import` within your Brocfile.

Or, you can fix you bower.json on 0.2.0 and upgrade later.

**Comment by btecu** [comment]
@jeancdc Make sure you don't have another addon relying on `ember-cli-moment-shim`.
In my case, I had `ember-bootstrap-datetimepicker` that uses the old version (`bower`).

**Comment by jeancdc** [comment]
Yes, I've uninstalled ember-bootstrap-datetimepicker and I don't have this problem anymore.
But I got it if I install the last version of this addon... Is there a solution ?

No problem with version 0.2.0 of ember-cli-moment-shim.

**Comment by jasonmit** [comment]
Not sure the question.  That error indicates something is trying to app import a file, moment-shim.js, that no longer exists as if 0.2.x.  No app imports are needed since this is now an addon and handles that for you.  You'll need to figure out if you or an addon you are consuming is doing that.

**Comment by jasonmit** [comment]
Also, do not bring this addon in via bower.  Like all addons these are npm deps.  If you track down the addons, I can send patches to them.

**Comment by jeancdc** [comment]
Furthermore, when I try to use the command `ember install ember-cli-moment-shim`, I've got 

```
Installed packages for tooling via npm.
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/lib/models/project.js:484:53
    at baseFindIndex (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/lodash/internal/baseFindIndex.js:16:9)
    at /Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/lodash/internal/createFind.js:18:19
    at Project.findAddonByName (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/lib/models/project.js:483:20)
    at Class.module.exports.Task.extend.findDefaultBlueprintName (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/lib/tasks/addon-install.js:64:30)
    at Class.module.exports.Task.extend.installBlueprint (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/lib/tasks/addon-install.js:53:30)
    at Class.<anonymous> (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/lib/tasks/addon-install.js:43:19)
    at lib$rsvp$$internal$$tryCatch (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
    at lib$rsvp$$internal$$publish (/Users/jeancreuzedeschatelliers/Developpement/Projets/contactsmanagement/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
```

**Comment by jasonmit** [comment]
What version of ember cli?

**Comment by jeancdc** [comment]
1.13.1

**Comment by jasonmit** [comment]
@jeancdc I threw together an example app with 1.13.1 and can't reproduce this with a fresh `ember new app`

Dug into it further, and discovered it's likely a bug in a dep of ember-cli that has been fixed: https://github.com/ember-cli/ember-cli/issues/4102#issuecomment-103099661

**Comment by mmahalwy** [comment]
im getting this now and cannot find the source of it :(

I think it's one of the deps but cannot determine which one

**Comment by jasonmit** [comment]
Start removing them one by one :\  It's not at all related to ember-cli-moment-shim.

**Comment by mmahalwy** [comment]
I don't remember how I resolved this, but it was something to do with an addon being outdated that had an older version of `ember-cli-moment-shim` throwing that error. Make sure your addons are up to date
