### ISSUE TITLE
includeTimezone: '2010-2020' not working with latest version of moment-timezone (0.5.12) because it ships with 2012-2022

### ISSUE THREAD

**Issue by urbany** [jasonmit/ember-cli-moment-shim#121]
Check: https://github.com/moment/moment-timezone/commit/78eb6bef64d5c046f18751566c5b8ff3a0ca1185#diff-42ba1d994f4fa8c6ad17a7efae7936ccR3

Not sure how this should be solved.
Should we start using `includeTimezone: '2012-2022'` and bump minimum `moment-timezone` dependency to 0.5.12?

**Comment by Blackening999** [comment]
My application in production showing next error:

```
The Broccoli Plugin: [Funnel] failed with:
Error: ENOENT: no such file or directory, lstat '/tmp/build_nnnn/proj-sdfsd80de6sdf/tmp/funnel-input_base_path-IIKfEciU.tmp/builds/moment-timezone-with-data-2010-2020.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:887:18)
    at FSMonitor._measure (/app/tmp/cache/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.lstatSync (/app/tmp/cache/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at symlink (/app/tmp/cache/node_modules/symlink-or-copy/index.js:79:26)
    at Function.symlinkOrCopySync [as sync] (/app/tmp/cache/node_modules/symlink-or-copy/index.js:65:5)
    at Funnel._copy (/app/tmp/cache/node_modules/broccoli-funnel/index.js:467:19)
    at Funnel.processFile (/app/tmp/cache/node_modules/broccoli-funnel/index.js:450:8)
    at Funnel.applyPatch [as _applyPatch] (/app/tmp/cache/node_modules/broccoli-funnel/index.js:367:12)
    at Funnel.<anonymous> (/app/tmp/cache/node_modules/broccoli-funnel/index.js:321:10)
The broccoli plugin was instantiated at: 
    at Funnel.Plugin (/app/tmp/cache/node_modules/broccoli-plugin/index.js:7:31)
    at new Funnel (/app/tmp/cache/node_modules/broccoli-funnel/index.js:58:10)
    at Class.module.exports.treeForBrowserVendor (/app/tmp/cache/node_modules/ember-cli-moment-shim/index.js:225:25)
    at Class.module.exports.treeForVendor (/app/tmp/cache/node_modules/ember-cli-moment-shim/index.js:142:19)
    at Class._treeFor (/app/tmp/cache/node_modules/ember-cli/lib/models/addon.js:371:33)
    at Class.treeFor (/app/tmp/cache/node_modules/ember-cli/lib/models/addon.js:339:21)
    at /app/tmp/cache/node_modules/ember-cli/lib/broccoli/ember-app.js:499:20
    at Array.map (native)
    at EmberApp.addonTreesFor (/app/tmp/cache/node_modules/ember-cli/lib/broccoli/ember-app.js:497:30)
    at EmberApp._processedVendorTree (/app/tmp/cache/node_modules/ember-cli/lib/broccoli/ember-app.js:948:29)
 !     Push rejected, failed to compile Ember CLI app.
 !     Push failed
```

**Comment by Blackening999** [comment]
Fix this ASAP please.
Don't want to fork because of it

**Comment by jasonmit** [comment]
@Blackening999 fork and patch like a good steward of the community.  Otherwise, lock your deps and wait for me, or someone else, to patch it.

I should be able to fix it tomorrow.

**Comment by makepanic** [comment]
What would be the way forward? 
I don't think we'd want ember-cli-moment-shim consumers to break because moment-timezone doesn't include the 2010-2020 build anymore. 

The issue is basically in the hardcoded value [here](https://github.com/jasonmit/ember-cli-moment-shim/blob/master/index.js#L213).
Adding a case for `2012-2022` and pointing to the correct file won't solve the issue for `2010-2020` users.
A solution could be to allow a keyword like `10-years` which always points to the most recent timezone 10 years data file.
Which causes issues as soon as moment-timezone updates again, because it'll break until someone updates the timezone file paths.

Btw the current workaround without forking ember-cli-moment-shim is to manually install `moment-timezone@0.5.11`.

**Comment by jasonmit** [comment]
@makepanic The way forward will be to match on moment-timezone-with-data-*.

I'll also introduce a new option in replace of `2010-2020` that best describes the decade of data.  For now, `2010-2020` will fallback to matching on `moment-timezone-with-data-*` so peoples builds stop breaking.  If you use 2010-2020 I'll throw a warning at build time mentioning the breaking change in momentjs' data.

This way in a few years when they rename the file again things will continue to just work.

**Comment by jasonmit** [comment]
I versioned 3.0.3 to lock moment-timezone to <= 0.5.11 until I find time to support >= 0.5.12

**Comment by jasonmit** [comment]
3.1.0 was released which adds wildcard support within the timezone data filename and deprecated "2010-2020" as an option in favor of "subset" which will scale better into the future.

**Comment by urbany** [comment]
@jasonmit thanks for the quick fix mate! Seems like something went wrong with the 3.1.0 release though. Latest vesion on NPM is still 3.0.3 - https://www.npmjs.com/package/ember-cli-moment-shim

**Comment by jasonmit** [comment]
@urbany I (re)published, should be good now.

**Comment by mcfiredrill** [comment]
Thanks for getting this fix out so quick
