### ISSUE TITLE
Bug found: can't define any configurations

### ISSUE THREAD

**Issue by nightire** [jasonmit/ember-cli-moment-shim#19]
Environment:
- Windows 10 Home Edition (win32 x64)
- node.js v4.2.2
- npm v2.14.7
- ember-cli v1.13.8

Descriptions:

After install ember-cli-moment-shim (or upgrade, I've tried a lot of times), if some custom configuration defined, `ember serve` will not success. For examples:

``` javascript
// config/environment.js
moment: {
  includeTimezone: 'all'
}
```

will causes:

```
ENOENT: no such file or directory, symlink 'C:\Users\Yu\Code\cloud.mei1.com\bower_components\moment-timezone\builds\mome
nt-timezone-with-data.min.js' -> 'C:\Users\Yu\Code\cloud.mei1.com\tmp\funnel-output_path-ruvaKEVz.tmp\moment-timezone\tz
.js'
Error: ENOENT: no such file or directory, symlink 'C:\Users\Yu\Code\cloud.mei1.com\bower_components\moment-timezone\buil
ds\moment-timezone-with-data.min.js' -> 'C:\Users\Yu\Code\cloud.mei1.com\tmp\funnel-output_path-ruvaKEVz.tmp\moment-time
zone\tz.js'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at symlinkWindows (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funnel\n
ode_modules\symlink-or-copy\index.js:90:16)
    at Function.symlinkOrCopySync [as sync] (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_mod
ules\broccoli-funnel\node_modules\symlink-or-copy\index.js:56:5)
    at Funnel._copy (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funnel\ind
ex.js:394:19)
    at Funnel.processFile (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funn
el\index.js:377:8)
    at Funnel.applyPatch [as _applyPatch] (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modul
es\broccoli-funnel\index.js:295:12)
    at Funnel.<anonymous> (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funn
el\index.js:247:10)
    at Array.forEach (native)
    at Funnel.processFilters (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-f
unnel\index.js:246:9)
```

and

``` javascript
// config/environment.js
moment: {
  includeLocales: ['zh-cn']
}
```

will causes:

```
ENOENT: no such file or directory, mkdir 'C:\Users\Yu\Code\cloud.mei1.com\tmp\funnel-output_path-q5DIRweY.tmp\moment\loc
ales'
Error: ENOENT: no such file or directory, mkdir 'C:\Users\Yu\Code\cloud.mei1.com\tmp\funnel-output_path-q5DIRweY.tmp\mom
ent\locales'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Funnel.applyPatch [as _applyPatch] (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modul
es\broccoli-funnel\index.js:288:10)
    at Funnel.<anonymous> (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funn
el\index.js:247:10)
    at Array.forEach (native)
    at Funnel.processFilters (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-f
unnel\index.js:246:9)
    at Funnel.build (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funnel\ind
ex.js:168:10)
    at C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\broccoli-funnel\node_modules\broc
coli-plugin\read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modules\bro
ccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\Yu\Code\cloud.mei1.com\node_modules\ember-cli-moment-shim\node_modul
es\broccoli-funnel\node_modules\broccoli-plugin\node_modules\promise-map-series\node_modules\rsvp\dist\rsvp.js:505:17)
```

but if set `includeLocales: true` will be ok.

All these settings above will all be fine under Mac OS X (same project), only errors occur under windows, I've tested this on windows 7 Ultimate Edition & windows 8/10 Home Edition.

**Comment by jasonmit** [comment]
I don't have a windows VM setup to test, this will take some time unless one can be provided.

**Comment by jasonmit** [comment]
I believe it to be related to https://github.com/broccolijs/broccoli-funnel/issues/53

In any case, I will attempt to resolve it by remove path.join and will need you to confirm it's working.

/cc @stefanpenner

**Comment by stefanpenner** [comment]
@jasonmit I'll be likely finishing that issue up in the AM

**Comment by jasonmit** [comment]
Closing since this should be resolved.  Please reopen if you it persists.

**Comment by nightire** [comment]
@jasonmit Thank you, bug seems resolved now.

**Comment by sethphillips** [comment]
I seem to still be experiencing this with version 0.6.2 on windows only.

**Comment by jasonmit** [comment]
Please use the latest version

**Comment by andersonlimasoa** [comment]
The Locale don't is working for me , in emberJS

my veresions:  

ember-cli: 2.10.0
node: 6.9.4
os: linux x64

this is my  // config/environment.js

```
	moment: {
    // To cherry-pick specific locale support into your application.
    // Full list of locales: https://github.com/moment/moment/tree/2.10.3/locale
    includeLocales: ['pt-br'],
		includeTimezone: 'none',
		format: 'DD/MM/YYYY',
		alert: 'teste',
    allowEmpty: true
   },
	 
```

in helper 
helpers/moment-from-now.js

import Ember from 'ember';
import config from '../config/environment';
import FromNowHelper from 'ember-moment/helpers/moment-from-now';

export function momentFromNow([value, ]/*, hash*/) {
  // moment.locale('pt-br');
  return moment(value).locale('pt-br').fromNow();
}

export default Ember.Helper.helper(momentFromNow);

// in my template.hbs

{{moment-from-now model.statusDate 'DD/MM/YYYY' locale='pt-br'}} 


can you help me  ?

**Comment by Andersonlimahw** [comment]
The Locale don't is working for me , in emberJS

my versions:  

ember-cli: 2.10.0
node: 6.9.4
os: linux x64

this is my  // config/environment.js

```
	moment: {
    // To cherry-pick specific locale support into your application.
    // Full list of locales: https://github.com/moment/moment/tree/2.10.3/locale
    includeLocales: ['pt-br'],
		includeTimezone: 'none',
		format: 'DD/MM/YYYY',
		alert: 'teste',
    allowEmpty: true
   },
	 
```

in helper 
helpers/moment-from-now.js

```
import Ember from 'ember';
import config from '../config/environment';
import FromNowHelper from 'ember-moment/helpers/moment-from-now';

export function momentFromNow([value, ]/*, hash*/) {
  // moment.locale('pt-br');
  return moment(value).locale('pt-br').fromNow();
}

```
export default Ember.Helper.helper(momentFromNow);

// in my template.hbs
`
{{moment-from-now model.statusDate 'DD/MM/YYYY' locale='pt-br'}} `


its render bug in en-us
can you help me  ?
